In [1]:
import pandas as pd

# matter_level_df = pd.read_csv("/home/azureuser/cloudfiles/code/production-data/8-Dec-2025/processed-data/matter-level-df.csv", 
#                               parse_dates=['submitted_on', 'due_on', 'created_on', 'activity_created_on'])
# matter_info = pd.read_csv("/home/azureuser/cloudfiles/code/production-data/8-Dec-2025/processed-data/matter-info.csv",
#                           parse_dates=['last_invoiced_on', 'last_paid_on' ,'last_statement_sent_on'])

#date columns: 
# matter_level_df -  submitted_on, due_on, created_on, activity_created_on, 
# matter_info - last_invoiced_o, last_paid_on ,last_statement_sent_on,

In [2]:
# matter_level_df.query("invoice_number == 3752526")

In [3]:
import numpy as np
import pandas as pd

PREFIX = '/home/azureuser/cloudfiles/code/production-data/12-dec-25/12-Dec-2025/tenant1-12-20-25'
OUTPUT_FILE = f'{PREFIX}-MASTER-REPORT.csv'

# invoices.csv: 100 samples
# #['client_id', 'matter_id', 'invoice_number', 'invoice_amount', 'ar_amount', 'submitted_on', 'due_on', 'days_overdue', 'status']
df_invoices = pd.read_csv(f'{PREFIX}-invoices.csv') 

# activities.csv: 
# #['client_id', 'matter_id', 'invoice_number', 'created_on', 'event_type', 'name', 'description']
df_activities = pd.read_csv(f'{PREFIX}-activities-REDACTED.csv')

# notes.csv: 
# #['client_id', 'matter_id', 'invoice_number', 'created_on', 'content']
df_notes = pd.read_csv(f'{PREFIX}-notes-REDACTED.csv')

# matters.csv: 
# #['client_id', 'matter_id', 'wip_amount', 'last_invoiced_on', 'last_paid_on', 'last_statement_sent_on', 'payment_terms_in_days', 'total_billed_amount', 'total_collected_amount', 'total_work_amount', 'ar_total', 'ar_overdue']
df_matters = pd.read_csv(f'{PREFIX}-matters.csv')

# clients.csv: 
# #['client_id', 'wip_amount', 'last_invoiced_on', 'last_action_on', 'last_paid_on', 'last_statement_sent_on', 'payment_terms_in_days', 'total_billed_amount', 'total_collected_amount', 'total_work_amount', 'ar_total', 'ar_overdue']
df_clients = pd.read_csv(f'{PREFIX}-clients.csv')

# messages.csv: 
# #['client_id', 'sent_on', 'subject', 'body']
df_messages = pd.read_csv(f'{PREFIX}-messages-REDACTED.csv')

In [4]:
df_matters.groupby(by = 'client_id').agg(list)

,matter_id,wip_amount,last_invoiced_on,last_paid_on,last_statement_sent_on,payment_terms_in_days,total_billed_amount,total_collected_amount,total_work_amount,ar_total,ar_overdue
client_id,,,,,,,,,,,
16,[0000016-0000163],[0.0],[2025-11-24],[2025-12-08 06:00:00+00],[nan],[nan],[5291.0],[4664.5],[5291.0],[626.5],[0.0]
2899,[0002899-0000035],[1862.32],[2025-12-19],[2025-12-16 06:00:00+00],[nan],[nan],[44804.23],[35802.5],[51422.05],[2876.0],[794.0]
13264,[0013264-0000002],[242.25],[2025-12-10],[2025-11-18 06:00:00+00],[nan],[nan],[307891.95],[304344.48],[314470.05],[484.5],[0.0]
14501,[0014501-0000057],[0.0],[2025-12-10],[2025-08-05 05:00:00+00],[nan],[nan],[801390.42],[801080.42],[804333.51],[310.0],[0.0]
17111,[0017111-0000098],[0.0],[2025-10-22],[2025-11-13 06:00:00+00],[nan],[nan],[59173.0],[19647.0],[60125.0],[39526.0],[39526.0]
...,...,...,...,...,...,...,...,...,...,...,...
6016852,"[6016852-0000220, 6016852-0000273]","[0.0, 0.0]","[2025-12-15, 2025-10-20]","[2025-10-08 05:00:00+00, 2025-10-08 05:00:00+00]","[nan, nan]","[nan, nan]","[35985.0, 5511.96]","[35755.0, 2066.14]","[38297.5, 5511.96]","[230.0, 3325.82]","[130.0, 3325.82]"
6050484,[6050484-0000023],[3899.22],[2025-11-09],[2025-09-09 05:00:00+00],[2025-12-19 16:11:14.588681+00],[nan],[598656.25],[539499.25],[654750.61],[59157.0],[59157.0]
6053054,[6053054-0000099],[2596.92],[2025-12-09],[2025-12-12 06:00:00+00],[2025-12-05 14:11:37.99618+00],[nan],[292774.54],[282375.54],[312479.46],[10399.0],[0.0]
6053056,[6053056-0000001],[773.0],[2025-12-12],[2025-11-20 06:00:00+00],[nan],[nan],[620656.07],[599418.07],[634565.57],[21238.0],[0.0]
6058243,[6058243-0000020],[0.0],[2025-10-15],[2025-10-06 05:00:00+00],[nan],[nan],[77467.82],[74917.4],[77710.82],[2550.42],[2550.42]

In [5]:
df_invoices.head(1)

,client_id,matter_id,invoice_number,invoice_amount,ar_amount,submitted_on,due_on,days_overdue,status
0,559974,0559974-0000001,3761402,76399.0,0.0,2025-06-23 04:00:00+00,2025-07-23,150,Delivered

In [8]:
df_invoices.groupby(by = "matter_id").agg(list)

,client_id,invoice_number,invoice_amount,ar_amount,submitted_on,due_on,days_overdue,status
matter_id,,,,,,,,
0000016-0000163,[16],[3858831-235132],[1353.0],[626.5],[2025-12-09 14:59:59.232466+00],[2026-02-22],[0],[Viewed]
0002899-0000035,[2899],[3781783],[14186.0],[0.0],[2025-07-25 14:03:04.325637+00],[2025-08-22],[120],[Viewed]
0013264-0000002,[13264],[3868917],[484.5],[484.5],[2025-12-12 17:05:18.49996+00],[2026-01-09],[0],[Viewed]
0014501-0000057,[14501],[3868951],[310.0],[310.0],[2025-12-12 17:06:15.571232+00],[2026-01-09],[0],[Viewed]
0017111-0000098,[17111],[3776754],[21721.0],[21721.0],[2025-07-22 13:17:42.695913+00],[2025-08-16],[126],[Delivered]
...,...,...,...,...,...,...,...,...
6016852-0000273,"[6016852, 6016852]","[3812559, 3835452]","[1243.82, 2082.0]","[1243.82, 2082.0]","[2025-11-21 18:30:07.9+00, 2025-11-21 18:39:40...","[2025-10-17, 2025-11-19]","[64, 31]","[Delivered, Delivered]"
6050484-0000023,"[6050484, 6050484, 6050484]","[3806523, 3823377, 3845276]","[1551.72, 1637.22, 1551.72]","[1551.72, 1637.22, 1551.72]","[2025-09-10 19:44:23.991055+00, 2025-10-06 23:...","[2025-10-09, 2025-11-05, 2025-12-09]","[72, 45, 11]","[Viewed, Viewed, Viewed]"
6053054-0000099,[6053054],[3868110],[10399.0],[10399.0],[2025-12-10 13:25:18.26553+00],[2026-01-08],[0],[Viewed]
6053056-0000001,"[6053056, 6053056]","[3841508, 3870407]","[18099.0, 3139.0]","[18099.0, 3139.0]","[2025-11-05 17:51:55.875407+00, 2025-12-12 16:...","[2025-12-30, 2026-02-10]","[0, 0]","[Delivered, Delivered]"
6058243-0000020,[6058243],[3831249],[12318.41],[2550.42],[2025-10-16 13:19:50.565534+00],[2025-11-14],[36],[Viewed]

In [65]:
invoice_number = 3752526
client_id = 577951

In [33]:
df_notes.query(f"invoice_number=={invoice_number}")

,client_id,matter_id,invoice_number,created_on,content
4532,577951,0577951-0000001,3752526.0,2025-10-06 08:00:04.257427+00,The invoice will be outstanding for 121 days o...
4533,577951,0577951-0000001,3752526.0,2025-09-06 08:00:03.316602+00,The invoice will be outstanding for 91 days on...
4534,577951,0577951-0000001,3752526.0,2025-08-07 08:00:00.927259+00,The invoice will be outstanding for 61 days on...

In [66]:
df_clients.query(f"client_id =={client_id}")

,client_id,wip_amount,last_invoiced_on,last_action_on,last_paid_on,last_statement_sent_on,payment_terms_in_days,total_billed_amount,total_collected_amount,total_work_amount,ar_total,ar_overdue
71,577951,2804.75,2025-11-11,2025-12-05 14:17:02.072304+00,2025-12-05 06:00:00+00,2025-12-05 14:17:02.072304+00,30,23779.26,14425.25,26584.01,9354.01,4273.26

In [68]:
str(df_notes.query(f"invoice_number == {invoice_number}")[['created_on', 'content']].to_records(index=False))

"[('2025-10-06 08:00:04.257427+00', 'The invoice will be outstanding for 121 days on <DateTime>.')\n ('2025-09-06 08:00:03.316602+00', 'The invoice will be outstanding for 91 days on <DateTime>.')\n ('2025-08-07 08:00:00.927259+00', 'The invoice will be outstanding for 61 days on <DateTime>.')]"

In [50]:
print(df_invoices.query(f"invoice_number=={invoice_number}").to_json(index = False, lines = True, orient = 'records'))

{"client_id":577951,"matter_id":"0577951-0000001","invoice_number":3752526,"invoice_amount":8093.25,"ar_amount":50.0,"submitted_on":"2025-06-09 04:00:00+00","due_on":"2025-07-09","days_overdue":152,"status":"Viewed"}

In [60]:
print(df_activities.query(f"invoice_number=={invoice_number}").dropna().drop(columns = ['client_id', 'matter_id', 'invoice_number']).to_markdown(index = False))

| activity_created_on           | event_type    | activity_name     | activity_description                                                        |
|:------------------------------|:--------------|:------------------|:----------------------------------------------------------------------------|
| 2025-10-20 16:04:11.08007+00  | Event         | Downloaded        | Invoice downloaded using the link delivered to [<Email>]                    |
| 2025-10-20 16:04:04.295604+00 | StatusChanged | Viewed            | Invoice viewed using the link delivered to [<Email>]                        |
| 2025-10-20 15:44:58+00        | StatusChanged | Delivered         | Delivered to <Email>.                                                       |
| 2025-10-20 15:44:56.854487+00 | Modified      | Shared            | Shared invoice to [<Email>].                                                |
| 2025-09-15 22:48:06+00        | StatusChanged | Email Opened      | Opened by <Email>                                                           |
| 2025-09-15 14:48:20+00        | StatusChanged | Delivered         | Delivered to <Email>.                                                       |
| 2025-09-15 14:48:18.704551+00 | Modified      | Shared            | Shared invoice to [<Email>].                                                |
| 2025-08-22 19:23:52+00        | StatusChanged | Email Opened      | Opened by <Email>                                                           |
| 2025-08-22 13:08:38+00        | StatusChanged | Delivered         | Delivered to <Email>.                                                       |
| 2025-08-22 13:08:35.235583+00 | Modified      | Shared            | Shared invoice to [<Email>].                                                |
| 2025-06-22 07:47:57.617165+00 | Modified      | Document uploaded | Uploaded document [Invoice_3752526.pdf], type: [Pdf], version: [<DateTime>] |

In [ ]:
def data_formatter(df_invoices, df_notes, df_activities, invoice_number):

    notes = df_notes.query(f"invoice_number == {invoice_number}")[['created_on', 'content']].to_records(index=False)
    invoice_data = df_invoices.query(f"invoice_number=={invoice_number}").to_json(index = False, lines = True, orient = 'records')
    activities = df_activities.query(f"invoice_number=={invoice_number}").dropna().drop(columns = ['client_id', 'matter_id', 'invoice_number']).to_markdown(index = False)

    formatted_text = f"""

    INVOICE DATA: 
    {invoice_data}

    NOTES: 
    {notes}

    ACTIVITIES: 
    {activities}

    I
    """

    return formatted_text

In [76]:
print(data_formatter(df_invoices, df_notes, df_activities, invoice_number = 3752526))

    INVOICE DATA:
    {"client_id":577951,"matter_id":"0577951-0000001","invoice_number":3752526,"invoice_amount":8093.25,"ar_amount":50.0,"submitted_on":"2025-06-09 04:00:00+00","due_on":"2025-07-09","days_overdue":152,"status":"Viewed"}


    NOTES:
    [('2025-10-06 08:00:04.257427+00', 'The invoice will be outstanding for 121 days on <DateTime>.')
 ('2025-09-06 08:00:03.316602+00', 'The invoice will be outstanding for 91 days on <DateTime>.')
 ('2025-08-07 08:00:00.927259+00', 'The invoice will be outstanding for 61 days on <DateTime>.')]

    ACTIVITIES:

    | activity_created_on           | event_type    | activity_name     | activity_description                                                        |
|:------------------------------|:--------------|:------------------|:----------------------------------------------------------------------------|
| 2025-10-20 16:04:11.08007+00  | Event         | Downloaded        | Invoice downloaded using the link delivered to [<Email>]                    |
| 2025-10-20 16:04:04.295604+00 | StatusChanged | Viewed            | Invoice viewed using the link delivered to [<Email>]                        |
| 2025-10-20 15:44:58+00        | StatusChanged | Delivered         | Delivered to <Email>.                                                       |
| 2025-10-20 15:44:56.854487+00 | Modified      | Shared            | Shared invoice to [<Email>].                                                |
| 2025-09-15 22:48:06+00        | StatusChanged | Email Opened      | Opened by <Email>                                                           |
| 2025-09-15 14:48:20+00        | StatusChanged | Delivered         | Delivered to <Email>.                                                       |
| 2025-09-15 14:48:18.704551+00 | Modified      | Shared            | Shared invoice to [<Email>].                                                |
| 2025-08-22 19:23:52+00        | StatusChanged | Email Opened      | Opened by <Email>                                                           |
| 2025-08-22 13:08:38+00        | StatusChanged | Delivered         | Delivered to <Email>.                                                       |
| 2025-08-22 13:08:35.235583+00 | Modified      | Shared            | Shared invoice to [<Email>].                                                |
| 2025-06-22 07:47:57.617165+00 | Modified      | Document uploaded | Uploaded document [Invoice_3752526.pdf], type: [Pdf], version: [<DateTime>] |

    I

In [4]:
# df_activities.dropna(subset = "invoice_number")
df_activities.rename(columns={'created_on':'activity_created_on', 'description':'activity_description', 'name':'activity_name'}, inplace=True)

In [5]:
## Merging invoices with notes data
df_invoice_notes = pd.merge(df_invoices, df_notes, on = 'invoice_number', how = 'inner')
df_invoice_notes.drop(columns = ['client_id_y', 'matter_id_y'], inplace = True)
df_invoice_notes

,client_id_x,matter_id_x,invoice_number,invoice_amount,ar_amount,submitted_on,due_on,days_overdue,status,created_on,content
0,577951,0577951-0000001,3752526,8093.25,50.0,2025-06-09 04:00:00+00,2025-07-09,152,Viewed,2025-10-06 08:00:04.257427+00,The invoice will be outstanding for 121 days o...
1,577951,0577951-0000001,3752526,8093.25,50.0,2025-06-09 04:00:00+00,2025-07-09,152,Viewed,2025-09-06 08:00:03.316602+00,The invoice will be outstanding for 91 days on...
2,577951,0577951-0000001,3752526,8093.25,50.0,2025-06-09 04:00:00+00,2025-07-09,152,Viewed,2025-08-07 08:00:00.927259+00,The invoice will be outstanding for 61 days on...
3,834128,0834128-0000003,3752462,2755.00,2755.0,2025-06-09 04:00:00+00,2025-07-09,152,Delivered,2025-10-06 08:00:04.257434+00,The invoice will be outstanding for 121 days o...
4,834128,0834128-0000003,3752462,2755.00,2755.0,2025-06-09 04:00:00+00,2025-07-09,152,Delivered,2025-09-06 08:00:03.316624+00,The invoice will be outstanding for 91 days on...
...,...,...,...,...,...,...,...,...,...,...,...
292,558416,0558416-0000002,3758561,2000.00,0.0,2025-06-17 04:00:00+00,2025-07-17,144,Delivered,2025-09-14 08:00:04.169512+00,The invoice will be outstanding for 91 days on...
293,558416,0558416-0000002,3758561,2000.00,0.0,2025-06-17 04:00:00+00,2025-07-17,144,Delivered,2025-08-15 08:00:03.099171+00,The invoice will be outstanding for 61 days <D...
294,577124,0577124-0000001,3758524,1386.50,1386.5,2025-06-17 04:00:00+00,2025-07-17,144,Delivered,2025-10-14 08:00:03.219952+00,The invoice will be outstanding for 121 days o...
295,577124,0577124-0000001,3758524,1386.50,1386.5,2025-06-17 04:00:00+00,2025-07-17,144,Delivered,2025-09-14 08:00:04.169479+00,The invoice will be outstanding for 91 days on...
296,577124,0577124-0000001,3758524,1386.50,1386.5,2025-06-17 04:00:00+00,2025-07-17,144,Delivered,2025-08-15 08:00:03.099117+00,The invoice will be outstanding for 61 days <D...

In [10]:
## Merging invoice, notes and activities
matter_level_df = pd.merge(df_invoice_notes, df_activities, on = 'invoice_number', how = 'inner')
matter_level_df.drop(columns = ['client_id', 'matter_id'], inplace = True)
matter_level_df.rename(columns= {"client_id_x": "client_id", "matter_id_x": "matter_id"}, inplace = True)
matter_level_df

,client_id,matter_id,invoice_number,invoice_amount,ar_amount,submitted_on,due_on,days_overdue,status,created_on,content,activity_created_on,event_type,activity_name,activity_description
0,577951,0577951-0000001,3752526,8093.25,50.0,2025-06-09 04:00:00+00,2025-07-09,152,Viewed,2025-10-06 08:00:04.257427+00,The invoice will be outstanding for 121 days o...,2025-10-20 16:04:11.08007+00,Event,Downloaded,Invoice downloaded using the link delivered to...
1,577951,0577951-0000001,3752526,8093.25,50.0,2025-06-09 04:00:00+00,2025-07-09,152,Viewed,2025-10-06 08:00:04.257427+00,The invoice will be outstanding for 121 days o...,2025-10-20 16:04:04.295604+00,StatusChanged,Viewed,Invoice viewed using the link delivered to [<E...
2,577951,0577951-0000001,3752526,8093.25,50.0,2025-06-09 04:00:00+00,2025-07-09,152,Viewed,2025-10-06 08:00:04.257427+00,The invoice will be outstanding for 121 days o...,2025-10-20 15:44:58+00,StatusChanged,Delivered,Delivered to <Email>.
3,577951,0577951-0000001,3752526,8093.25,50.0,2025-06-09 04:00:00+00,2025-07-09,152,Viewed,2025-10-06 08:00:04.257427+00,The invoice will be outstanding for 121 days o...,2025-10-20 15:44:56.854487+00,Modified,Shared,Shared invoice to [<Email>].
4,577951,0577951-0000001,3752526,8093.25,50.0,2025-06-09 04:00:00+00,2025-07-09,152,Viewed,2025-10-06 08:00:04.257427+00,The invoice will be outstanding for 121 days o...,2025-10-06 08:00:04.562346+00,Modified,Note created,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22279,577124,0577124-0000001,3758524,1386.50,1386.5,2025-06-17 04:00:00+00,2025-07-17,144,Delivered,2025-08-15 08:00:03.099117+00,The invoice will be outstanding for 61 days <D...,2025-07-14 08:00:42.593094+00,Modified,Note created,NaN
22280,577124,0577124-0000001,3758524,1386.50,1386.5,2025-06-17 04:00:00+00,2025-07-17,144,Delivered,2025-08-15 08:00:03.099117+00,The invoice will be outstanding for 61 days <D...,2025-07-01 04:57:38.515867+00,StatusChanged,Marked as submitted,NaN
22281,577124,0577124-0000001,3758524,1386.50,1386.5,2025-06-17 04:00:00+00,2025-07-17,144,Delivered,2025-08-15 08:00:03.099117+00,The invoice will be outstanding for 61 days <D...,2025-06-22 07:16:02.540988+00,Modified,Document uploaded,"Uploaded document [Invoice_3758524.pdf], type:..."
22282,577124,0577124-0000001,3758524,1386.50,1386.5,2025-06-17 04:00:00+00,2025-07-17,144,Delivered,2025-08-15 08:00:03.099117+00,The invoice will be outstanding for 61 days <D...,2025-06-19 14:20:54.016081+00,Modified,Created in Oddr,NaN
22283,577124,0577124-0000001,3758524,1386.50,1386.5,2025-06-17 04:00:00+00,2025-07-17,144,Delivered,2025-08-15 08:00:03.099117+00,The invoice will be outstanding for 61 days <D...,2025-06-17 04:00:00+00,StatusChanged,Finalized,NaN

In [11]:
matter_level_df.to_csv("/home/azureuser/cloudfiles/code/production-data/8-Dec-2025/processed-data/matter-level-df.csv", index = False)

In [13]:
df_matters.to_csv("/home/azureuser/cloudfiles/code/production-data/8-Dec-2025/processed-data/matter-info.csv", index = False)

In [8]:
['client_id_x', 'matter_id_x', 'invoice_number', 'invoice_amount',
       'ar_amount', 'submitted_on', 'due_on', 'days_overdue', 'status',
       'created_on', 'content', 'activity_created_on', 'event_type',
       'activity_name', 'activity_description']

['client_id_x',
 'matter_id_x',
 'invoice_number',
 'invoice_amount',
 'ar_amount',
 'submitted_on',
 'due_on',
 'days_overdue',
 'status',
 'created_on',
 'content',
 'activity_created_on',
 'event_type',
 'activity_name',
 'activity_description']

In [7]:
matter_level_df.columns

Index(['client_id_x', 'matter_id_x', 'invoice_number', 'invoice_amount',
       'ar_amount', 'submitted_on', 'due_on', 'days_overdue', 'status',
       'created_on', 'content', 'activity_created_on', 'event_type',
       'activity_name', 'activity_description'],
      dtype='object')

In [37]:
np.intersect1d(matter_level_df.matter_id_x, df_matters.matter_id).shape

(96,)

In [ ]:
import math 

df_notes['created_on'] = pd.to_datetime(df_notes['created_on'], errors='ignore')
df_notes.sort_values(by = 'created_on', ascending=False, inplace=True, ignore_index=True)
df_notes['invoice_number'] = df_notes['invoice_number'].apply(lambda x: int(x) if not math.isnan(x) else -1)
df_notes['content_with_timestamps'] = df_notes['created_on'] + ": " + df_notes['content']
df_notes.head()

In [ ]:
df_notes.query("invoice_number == 3750827")

In [ ]:
df_test = df_notes.dropna(subset = 'matter_id').groupby("matter_id").agg(set)
df_test

In [ ]:
# matter_notes_df = pd.merge(
#     df_matters, df_notes, 
#     on = ['client_id', 'matter_id'], 
#     how = 'inner')[["client_id", "matter_id", "invoice_number", "created_on", "content", "total_billed_amount", "total_work_amount", "wip_amount", "ar_total", "total_collected_amount", "ar_overdue", "payment_terms_in_days", "last_invoiced_on", "last_statement_sent_on", "last_paid_on"]]

# matter_notes_df

In [ ]:
# matter_notes_df = pd.merge(
#     df_matters, df_notes, 
#     on = ['client_id', 'matter_id'], 
#     how = 'inner')[["client_id", "matter_id", "invoice_number", "created_on", "content", "total_billed_amount", "total_work_amount", "wip_amount", "ar_total", "total_collected_amount", "ar_overdue", "payment_terms_in_days", "last_invoiced_on", "last_statement_sent_on", "last_paid_on"]]

# matter_notes_df

In [ ]:
from functools import reduce

# clients -- notes
print("Clients & Notes:", np.intersect1d(df_clients.client_id, df_notes.client_id).shape)

print(np.intersect1d(df_clients.client_id, df_matters.client_id))

print(reduce(np.intersect1d, (df_clients.client_id, df_matters.client_id, df_notes.client_id, df_activities.client_id,)))