In [1]:
import dspy
import os
from dotenv import load_dotenv
from openinference.instrumentation.dspy import DSPyInstrumentor
from langfuse import get_client

load_dotenv("/home/azureuser/cloudfiles/code/email-generation/.env.local", override=True)

os.environ["LANGFUSE_PUBLIC_KEY"] = os.getenv("LANGFUSE_PUBLIC_KEY")
os.environ["LANGFUSE_SECRET_KEY"] = os.getenv("LANGFUSE_SECRET_KEY")
os.environ["LANGFUSE_BASE_URL"] = "http://localhost:3000"

langfuse = get_client()
import openlit
openlit.init(tracer=langfuse._otel_tracer, disable_batch=True)

In [ ]:
api_key = os.getenv("AZURE_OPENAI_API_KEY")
api_base = os.getenv("AZURE_LANGUAGE_ENDPOINT")
api_version = os.getenv("AZURE_API_VERSION")
deployment_name = os.getenv("AZURE_OPENAI_DEPLOYMENT_NAME")

lm_4o_mini = dspy.LM(
    model=f"azure/{os.getenv('AZURE_OPENAI_DEPLOYMENT_NAME')}",
    api_key=api_key,
    api_base=api_base,
    # api_version=os.getenv("AZURE_OPENAI_API_VERSION"),
    temperature=0.8, 
    model_type='responses'
)

lm_5_mini = dspy.LM( 
    model=f"azure/gpt-5-mini",
    api_key=os.getenv("AZURE_OPENAI_4_1_KEY"),
    api_base=api_base,
    # api_version="2025-04-14",
    temperature=1, 
    model_type='responses'
)

lm_41_mini = dspy.LM(
    model=f"azure/gpt-4.1-mini",
    api_key=os.getenv("AZURE_OPENAI_4_1_KEY"),
    api_base=api_base,
    # api_version="2025-04-14",
    temperature=0.4, 
    model_type='responses'
)

# mistral = dspy.LM(
#     model="openai/mistral-small-2503",
#     api_key=os.getenv("AZURE_MISTRAL_KEY"),
#     api_base="https://anuj-ai-resource.services.ai.azure.com/openai/v1/",
#     api_version="2024-05-01-preview",
#     temperature=0.8, 
#     # model_type='responses'
# )

# phi4 = dspy.LM(
#     model="openai/Phi-4-reasoning",
#     api_key=os.getenv("AZURE_MISTRAL_KEY"),
#     api_base="https://anuj-ai-resource.services.ai.azure.com/openai/v1/",
#     api_version="2024-05-01-preview",
#     temperature=0.8, 
#     # model_type='responses'
# )

dspy.configure(lm=lm_41_mini)

In [3]:
import pandas as pd

# matter_level_df = pd.read_csv("/home/azureuser/cloudfiles/code/production-data/8-Dec-2025/processed-data/matter-level-df.csv", 
#                               parse_dates=['submitted_on', 'due_on', 'created_on', 'activity_created_on'])
# matter_info = pd.read_csv("/home/azureuser/cloudfiles/code/production-data/8-Dec-2025/processed-data/matter-info.csv",
#                           parse_dates=['last_invoiced_on', 'last_paid_on' ,'last_statement_sent_on'])

#date columns: 
# matter_level_df -  submitted_on, due_on, created_on, activity_created_on, 
# matter_info - last_invoiced_o, last_paid_on ,last_statement_sent_on,  

PREFIX = '/home/azureuser/cloudfiles/code/production-data/12-dec-25/tenant1-12-20-25'
OUTPUT_FILE = f'{PREFIX}-MASTER-REPORT.csv'

# invoices.csv: 100 samples
# #['client_id', 'matter_id', 'invoice_number', 'invoice_amount', 'ar_amount', 'submitted_on', 'due_on', 'days_overdue', 'status']
df_invoices = pd.read_csv(f'{PREFIX}-invoices.csv') 

# activities.csv: 
# #['client_id', 'matter_id', 'invoice_number', 'created_on', 'event_type', 'name', 'description']
df_activities = pd.read_csv(f'{PREFIX}-activities-REDACTED.csv', parse_dates = ['created_on'], date_format='%Y-%m-%d %H:%M:%S.%f%z')

# notes.csv: 
# #['client_id', 'matter_id', 'invoice_number', 'created_on', 'content']
df_notes = pd.read_csv(f'{PREFIX}-notes-REDACTED.csv', parse_dates=['created_on'])
df_notes['created_on'] = pd.to_datetime(df_notes['created_on'], format = 'mixed')
df_notes = df_notes.dropna()
df_notes['invoice_number'] = df_notes['invoice_number'].apply(lambda x: int(x))
df_notes.head()
# df_notes['invoice_number'] = df_notes['invoice_number'].astype(str)

# matters.csv: 
# #['client_id', 'matter_id', 'wip_amount', 'last_invoiced_on', 'last_paid_on', 'last_statement_sent_on', 'payment_terms_in_days', 'total_billed_amount', 'total_collected_amount', 'total_work_amount', 'ar_total', 'ar_overdue']
df_matters = pd.read_csv(f'{PREFIX}-matters.csv', parse_dates=['last_invoiced_on', 'last_statement_sent_on'], date_format='%Y-%m-%d %H:%M:%S.%f%z')

# clients.csv: 
# #['client_id', 'wip_amount', 'last_invoiced_on', 'last_action_on', 'last_paid_on', 'last_statement_sent_on', 'payment_terms_in_days', 'total_billed_amount', 'total_collected_amount', 'total_work_amount', 'ar_total', 'ar_overdue']
df_clients = pd.read_csv(f'{PREFIX}-clients.csv', parse_dates=['last_invoiced_on', 'last_action_on', 'last_paid_on', 'last_statement_sent_on'], date_format='%Y-%m-%d %H:%M:%S.%f%z')

df_messages = pd.read_csv(f'{PREFIX}-messages-REDACTED.csv')

In [4]:
df_messages

,client_id,sent_on,subject,body
0,16,2025-09-26 14:35:04+00,RE: 2nd REQUEST: Legal invoice from <Organizat...,"Thank you again for all of your assistance, Jo..."
1,562116,2025-10-29 15:31:20+00,RE: Your October 2025 Invoice from <Organization>,"Invoice Submission (External)Hi <Person>, I ho..."
2,567518,2025-08-28 19:35:07+00,Re: **REPLY REQUESTED** <Organization> (056751...,[EXTERNAL EMAIL]\ndone!\napologies for the del...
3,567518,2025-08-28 12:34:41.720362+00,RE: **REPLY REQUESTED** <Organization>/<Organi...,Good morning <Person> Could I please ask you t...
4,580679,2025-12-02 19:08:27+00,Re: Husch Blackwell Invoice - <Organization>,[EXTERNAL EMAIL]\nSuper - thanks! <Person>. +4...

In [5]:
df_notes

,client_id,matter_id,invoice_number,created_on,content
1953,16,0000016-0000163,3858831,2025-11-25 19:29:53.511774+00:00,Waiting for AR to add the unallocated on the b...
1954,16,0000016-0000163,3814158,2025-09-18 20:23:50.024062+00:00,"<DateTime> email to <Person> for claim number,..."
1955,16,0000016-0000164,3814159,2025-09-18 20:24:16.115800+00:00,"<DateTime> email to <Person> for claim number,..."
2150,2899,0002899-0000034,3741724,2025-09-16 21:17:31.990738+00:00,<DateTime> - K<Person> - client has requested ...
2151,2899,0002899-0000035,3741755,2025-09-16 21:21:47.080575+00:00,<DateTime> - <Person> - Client response states...
...,...,...,...,...,...
7461,6053054,6053054-0000099,3830477,2025-10-24 14:26:35.535868+00:00,<DateTime> updated cost narratives to include ...
7462,6053054,6053054-0000099,3808607,2025-09-19 20:41:12.948517+00:00,"<DateTime> per <Person>, <Person> to email to ..."
7463,6053054,6053054-0000100,3868113,2025-12-15 18:03:29.562652+00:00,<DateTime> manually sent updated copy of invoi...
7519,6053056,6053056-0000001,3786289,2025-08-07 15:57:07.469024+00:00,Invoice delivery pending update of invoice del...
7520,6053056,6053056-0000001,3786289,2025-08-06 14:46:20.397062+00:00,Invoice delivery pending confirmation from cli...

In [6]:
df_summaries = pd.read_csv("/home/azureuser/cloudfiles/code/production-data/client_summarization_stored_completions_5th_feb26.csv")
df_summaries.head()

,completion_id,input_data,output_data
0,chatcmpl-D5OhEPBr9feteTKHFVqVPDGomJmFo,SyncCursorPage[ChatCompletionStoreMessage](dat...,"{\n ""id"": ""chatcmpl-D5OhEPBr9feteTKHFVqVPDGom..."
1,chatcmpl-D5Ew1ShgFECUweV0bORKx04cWf8uA,SyncCursorPage[ChatCompletionStoreMessage](dat...,"{\n ""id"": ""chatcmpl-D5Ew1ShgFECUweV0bORKx04cW..."
2,chatcmpl-D5EObN6Z1kzjxrZU2Mx7Wd0OkYq0p,SyncCursorPage[ChatCompletionStoreMessage](dat...,"{\n ""id"": ""chatcmpl-D5EObN6Z1kzjxrZU2Mx7Wd0Ok..."
3,chatcmpl-D5ENMYYiOXfT2iEM23SLnJ21at8M1,SyncCursorPage[ChatCompletionStoreMessage](dat...,"{\n ""id"": ""chatcmpl-D5ENMYYiOXfT2iEM23SLnJ21a..."
4,chatcmpl-D5BZKOuyVuimv1c0g4dKPJzdmTNZR,SyncCursorPage[ChatCompletionStoreMessage](dat...,"{\n ""id"": ""chatcmpl-D5BZKOuyVuimv1c0g4dKPJzdm..."

In [7]:
df_summaries.shape

(20, 3)

In [8]:
import ast
import json
import re

MSG_RE = re.compile(r"ChatCompletionStoreMessage\(content='((?:\\.|[^'])*)'.*?role='(.*?)'", re.DOTALL)

def _unescape_python_string(raw: str) -> str:
    try:
        return ast.literal_eval("'" + raw + "'")
    except Exception:
        return bytes(raw, 'utf-8').decode('unicode_escape', errors='replace')

def _split_user_content(content: str):
    if not content:
        return '', '', ''
    normalized = content.replace('\r\n', '\n')
    fin_key = 'Financial data:\n'
    notes_key = '\n\nNotes:\n'
    if fin_key not in normalized:
        return normalized.strip(), '', ''
    prompt, rest = normalized.split(fin_key, 1)
    financial_data = rest
    notes = ''
    if notes_key in rest:
        financial_data, notes = rest.split(notes_key, 1)
    return prompt.strip(), financial_data.strip(), notes.strip()

def parse_input_data(input_data: str):
    if not isinstance(input_data, str):
        return {'system_prompt': '', 'user_prompt': '', 'financial_data': '', 'notes': ''}
    messages = []
    for match in MSG_RE.finditer(input_data):
        raw = match.group(1)
        role = match.group(2)
        content = _unescape_python_string(raw)
        messages.append((role, content))
    system_prompt = '\n\n'.join([c for r, c in messages if r == 'system']).strip()
    user_content = '\n\n'.join([c for r, c in messages if r == 'user']).strip()
    user_prompt, financial_data, notes = _split_user_content(user_content)
    return {
        'system_prompt': system_prompt,
        'user_prompt': user_prompt,
        'financial_data': financial_data,
        'notes': notes,
    }

def parse_output_data(output_data: str) -> str:
    if not isinstance(output_data, str) or not output_data:
        return ''
    cleaned = re.sub(r':\s*<([^>]+)>', r': "<\1>"', output_data)
    try:
        payload = json.loads(cleaned)
        return payload.get('choices', [{}])[0].get('message', {}).get('content', '')
    except Exception:
        match = re.search(r'\"content\"\s*:\s*\"((?:\\.|[^\"])*)\"', output_data, re.DOTALL)
        if not match:
            return ''
        return bytes(match.group(1), 'utf-8').decode('unicode_escape', errors='replace')

parsed_rows = df_summaries['input_data'].apply(parse_input_data)
df_parsed = pd.DataFrame(list(parsed_rows))
df_extracted = pd.concat([
    df_summaries[['completion_id']].copy(),
    df_parsed,
    df_summaries['output_data'].apply(parse_output_data).rename('output_summary'),
], axis=1)


df_extracted.head()

,completion_id,system_prompt,user_prompt,financial_data,notes,output_summary
0,chatcmpl-D5OhEPBr9feteTKHFVqVPDGomJmFo,"You are Oddr Summarizer, an AI assistant that ...",Given a client with the following financial da...,"The client has 1 active invoices, lifetime bil...","ClientId,MatterId,InvoiceNumber,Content,CreatedOn","The client currently has **$20,806.67** in ove..."
1,chatcmpl-D5Ew1ShgFECUweV0bORKx04cWf8uA,"You are Oddr Summarizer, an AI assistant that ...",Given a client with the following financial da...,"The client has 3 active invoices, lifetime bil...","ClientId,MatterId,InvoiceNumber,Content,Create...","The client currently has **$16,373.00** in ove..."
2,chatcmpl-D5EObN6Z1kzjxrZU2Mx7Wd0OkYq0p,"You are Oddr Summarizer, an AI assistant that ...",Given a client with the following financial da...,"The client has 2 active invoices, lifetime bil...","ClientId,MatterId,InvoiceNumber,Content,Create...","The client currently has **$6,096.75** in over..."
3,chatcmpl-D5ENMYYiOXfT2iEM23SLnJ21at8M1,"You are Oddr Summarizer, an AI assistant that ...",Given a client with the following financial da...,"The client has 2 active invoices, lifetime bil...","ClientId,MatterId,InvoiceNumber,Content,Create...","The client currently has **$6,096.75** in over..."
4,chatcmpl-D5BZKOuyVuimv1c0g4dKPJzdmTNZR,"You are Oddr Summarizer, an AI assistant that ...",Given a client with the following financial da...,"The client has 3 active invoices, lifetime bil...","ClientId,MatterId,InvoiceNumber,Content,Create...","The client currently has **$16,373.00** in ove..."

In [9]:
import tiktoken

encoding = tiktoken.get_encoding("cl100k_base")
df_extracted['notes_token_count'] = df_extracted['notes'].apply(lambda x: len(encoding.encode(x)))

In [10]:
# df_extracted.to_csv("/home/azureuser/cloudfiles/code/production-data/stored_completions_5-feb.csv", index = False)

In [11]:
notes = df_extracted.notes.tolist()

In [12]:
df_extracted.financial_data.tolist()[2]

'The client has 2 active invoices, lifetime billed amount of $10,037.91, lifetime collected amount of $3,941.16, WIP of $0.00, overdue AR of $6,096.75, outstanding AR of $6,096.75, average DSO of 260.'

In [13]:
df_extracted.notes.tolist()[1]

'ClientId,MatterId,InvoiceNumber,Content,CreatedOn\n033546,,,"Forwarded 1<DateTime> email to client re invoices <PhoneNumber>, <PhoneNumber> &amp; <PhoneNumber> and if we need to make further changes, in light of them paying the December and January invoices.",02/03/2026\n033546,,,"Forwarded 1/6 email to K. Borowik asking him to fix the address and I will send to client. Sent revised invoices to client, asking if that works for them.",<DateTime>\n033546,,,"Emailed K. Borowik asking him to revise invoices <PhoneNumber>, <PhoneNumber> &amp; 585916 and I will send to client asking if that format is acceptable. (Putting the property address in the client address.)",01/06/2026\n033546,,,"Emailed L. Schleicher re September invoices <PhoneNumber>, <PhoneNumber> L<Person> resubmitted <DateTime>, noting they paid a November invoice <DateTime>. Emailed client re same.",<DateTime>\n033546,,,Emailed L. Schleicher re client paid the October invoices leaving two September invoices open. <Person> replied we submit the invoices through an online portal. <Person> resubmitted them.,<DateTime>\n033546,,,"<DateTime> Per <Person> contact <Person> <Email>  not Madeline Hall <DateTime>- Per <Person> &lt;<Email>&gt; is the new contact \nImported from 3E collections",08/28/2025\n033546,,,"AP:  REW - Emailed client re May invoice <PhoneNumber>. Client replied they will get it processed right away. \nImported from 3E collections",<DateTime>\n033546,,,"AP, Myrna:  REW - Emailed AP asking for payment status. 1/31 REW - Emailed client re: we did not receive payment as promised on <DateTime>. Client replied, noting that because of the amounts, they had to thru multiple levels of approval. <DateTime> REW - Emailed client thanking her for payment of November invoice and asking about payment status of the September and October invoices. She replied they will be paid <DateTime>. \nImported from 3E collections",02/13/2025\n033546,,,"Ap-Myrna:  REW - Emailed client re: we did not receive payment as promised on <DateTime>. Client replied, noting that because of the amounts, they had to thru multiple levels of approval. <DateTime> REW - Emailed client thanking her for payment of November invoice and asking about payment status of the September and October invoices. She replied they will be paid <DateTime>. \nImported from 3E collections",01/31/2025\n033546,,,"Myrna:  REW - Emailed client thanking her for payment of November invoice and asking about payment status of the September and October invoices. <DateTime> REW - Emailed <Organization> to find out when invoices will be paid. <DateTime> REW - Forwarded 12<DateTime> email to client asking for payment amount and date. Client forwarded email internally (<Email>) to advise us on payment. <Organization> said they needed revised invoices with a different address on it (which we already provided). Resent revised invoices. <Organization> replied they are all in process. <DateTime> REW - Emailed <Person> with list of open invoices asking if we can reach out. Emailed client with reminder statement. <DateTime> Dceen- Emailed <Person> asking to assist on Sept invoice #5827584, #5827585 and #5827586, Per L. <Person> contact <Person> <Email>  not Madeline <Person>, emailed client Per client: new contact <Person> &lt;<Email>&gt;, she forwarded invoices \nImported from 3E collections",01/14/2025\n033546,,,"<Person>, AP:  REW - Emailed <Organization> to find out when invoices will be paid. <DateTime> REW - Forwarded 12<DateTime> email to client asking for payment amount and date. Client forwarded email internally (<Email>) to advise us on payment. <Organization> said they needed revised invoices with a different address on it (which we already provided). Resent revised invoices. <Organization> replied they are all in process. <DateTime> REW - Emailed <Person> with list of open invoices asking if we can reach out. Emailed client with reminder statement. <DateTime> Dceen- Emailed <Person> asking to assist on Sept invoice #5827584, #5827585 and #5827586, Per <Person> contact <Person> <Email>  not <Person>, emailed client Per client: new contact <Person> &lt;<Email>&gt;, she forwarded invoices \nImported from 3E collections",12/30/2024\n033546,,,"<Person>:  REW - Forwarded <DateTime> email to client asking for payment amount and date. Client forwarded email internally (<Email>) to advise us on payment. <Organization> said they needed revised invoices with a different address on it (which we already provided). Resent revised invoices. <Organization> replied they are all in process. <DateTime> REW - Emailed <Person> with list of open invoices asking if we can reach out. Emailed client with reminder statement. <DateTime> Dceen- Emailed <Person> asking to assist on Sept invoice #5827584, #5827585 and #5827586, Per <Person> contact <Person> <Email>  not <Person>, emailed client Per client: new contact <Person> &lt;<Email>&gt;, she forwarded invoices \nImported from 3E collections",12/19/2024\n033546,,,"<Person>:  REW - Emailed <Person> with list of open invoices asking if we can reach out. Emailed client with reminder statement. <DateTime> Dceen- Emailed <Person> asking to assist on Sept invoice #5827584, #5827585 and #5827586, Per L. <Person> contact <Person> <Email>  not Madeline Hall, emailed client Per client: new contact Albert <Person> &lt;<Email>&gt;, she forwarded invoices \nImported from 3E collections",12/10/2024\n033546,,,"L<Person>:  Dceen- Emailed L. <Person> asking to assist on Sept invoice #5827584, #5827585 and #5827586, Per L. <Person> contact <Person> <Email>  not Madeline Hall, emailed client Per client: new contact Albert <Person> &lt;<Email>&gt;, she forwarded invoices \nImported from 3E collections",11/15/2024\n033546,,,"Madeline Hall:  REW - Emailed <Person> re July invoice <PhoneNumber>, noting the other July invoices and the August invoice were already paid. <Person> emailed client. Client replied <DateTime> she sent to corporate and will follow up. \nImported from 3E collections",09/16/2024\n033546,,,"L<Person>:  REW - Emailed L. <Person> re December and January invoices and if she has heard from the client. <Person> replied <DateTime> that they send a reminder statement on <DateTime>. If no payment by 4/30, email <Person> again. \nImported from 3E collections",<DateTime>\n033546,,,"R. White:  REW - Client finally ironed out payment problems. If no payment on December invoice by 3/15, email <Person>. \nImported from 3E collections",<DateTime>\n033546,,,"<Person>, <Person>:  REW - Emailed <Person> re balance <DateTime> $16,816.29 and we haven\'t received any payments. <Person> emailed client. Client replied <DateTime>, ""Please contact <Person> or <Person> re payment issues."" <DateTime> REW - Emailed <Person> asking if I can reach out to client about August-December invoices. <Person> reached out to client. Client will check on payment. <DateTime> REW - Emailed <Person> re August and September invoices and included a/r reminder statement. She replied client is ""really scattered"" but she will press on them <DateTime> after she gets a document to them. <DateTime> REW - Emailed <Person> re August invoices <PhoneNumber> &amp; <PhoneNumber>. <Person> will reach out. \nImported from 3E collections",<DateTime>\n033546,,,"L. Schleicher:  REW - Emailed L. <Person> asking if I can reach out to client about August-December invoices. <Person> reached out to client. Client will check on payment. <DateTime> REW - Emailed <Person> re August and September invoices and included a/r reminder statement. She replied client is ""really scattered"" but she will press on them <DateTime> after she gets a document to them. <DateTime> REW - Emailed <Person> re August invoices <PhoneNumber> &amp; <PhoneNumber>. <Person> will reach out. \nImported from 3E collections",12/20/2023\n033546,,,"L. Schleicher:  REW - Emailed L. <Person> re August and September invoices and included a/r reminder statement. She replied client is ""really scattered"" but she will press on them <DateTime> after she gets a document to them. <DateTime> REW - Emailed <Person> re August invoices <PhoneNumber> &amp; <PhoneNumber>. <Person> will reach out. \nImported from 3E collections",12/01/2023\n033546,,,"L. <Person>:  REW - Emailed <Person> re August invoices <PhoneNumber> &amp; <PhoneNumber>. <Person> will reach out. \nImported from 3E collections",10/09/2023'

In [14]:
df_extracted.output_summary.tolist()[0]

'The client currently has **$20,806.67** in overdue accounts receivable with no payments collected or billed to date, indicating a significant delay in payment processing. There are no recent interactions or updates noted, suggesting a lack of follow-up on this outstanding invoice. Given the average Days Sales Outstanding (DSO) of **4**, immediate outreach is recommended to address the overdue balance and initiate payment discussions. It is crucial to monitor this account closely to prevent further delays and ensure timely resolution.'

In [15]:
import numpy as np

overlapping_invoices = np.intersect1d(df_notes.invoice_number, df_invoices.invoice_number.tolist()).tolist()
print("Total: ", len(overlapping_invoices), overlapping_invoices)

Total:  43 ['3750401', '3764007', '3769975', '3778983', '3779715', '3781783', '3782861', '3787068', '3790207', '3791993', '3792487', '3794224', '3794436', '3794925', '3795448', '3800269', '3800572', '3802099', '3808989', '3811927', '3812559', '3814420', '3815886', '3816783', '3817152', '3819232', '3819674', '3821183', '3825917', '3828055', '3834273', '3835452', '3839511', '3841423', '3848860', '3851985', '3853210', '3854555', '3858890', '3860477', '3864673', '3868951', '3873403']

In [16]:
import dspy
from typing import Literal, List

class ClientSummarization(dspy.Signature):
    """
    You are Oddr Summarizer, an AI assistant that helps law firms manage their Accounts Receivable. Your job is to generate clear, concise, and helpful summaries for attorneys using only the facts provided.

    You may infer logical next steps or patterns (e.g., payment gaps, lack of follow-up), but do not fabricate or invent any client interactions or internal updates that aren’t explicitly present in the input.

    If no notes are available, avoid referring to interactions. Focus only on AR status and suggest possible outreach or monitoring based on the financial data.

    Your tone should be professional, factual, and efficient — like a trusted human AR professional writing a briefing. Favor direct, punchy sentences over formal or padded language.

    Given a client with the following financial data, notes and email conversations across the client, its matters, and invoices, please summarize the client in a way that will make it digestible and meaningful to the time-constrained Attorney responsible for the client so they can understand what is going on with their AR and who is responsible for any next steps.

    Frame this as a timeline, starting with an overview of the client’s current AR status, then highlighting the most recent interaction and any key themes from earlier interactions — but only if such notes are present. Do not fabricate or infer specific updates. However, it’s acceptable to suggest likely follow-up steps or highlight the absence of recent activity if that pattern is evident.

    Reduce repetitive details by grouping similar updates, eliminate specific payment amounts where appropriate, and keep the summary focused and efficient. Mention past events only if they are essential to understanding the current delay or next step. Avoid repeating older context that does not affect present action.

    Format the summary as a single paragraph without any headings or titles, and use smart **bolding** to highlight key points. 
    Limit the summary to **4 complete, efficient sentences**. Favor punchy, high-signal writing over formal explanations. 
    **Do not use headings, bullet points, or labels.** **Mention date always like Jan 01,2025**
    
    Structure the summary as a single flowing paragraph that follows this order:
    [AR overview]
    [Highlights from recent interactions — only if present]
    [Relevant context from earlier interactions — only if helpful]
    [Next steps or follow-up actions]
    """

    financial_data: str = dspy.InputField(
        desc="Structured csv containing Invoice Numbers, Dates, Amounts Outstanding, "
             "and total balance. These figures are immutable facts."
    )

    notes: str = dspy.InputField(
        desc="Mixed timeline of client interaction, internal attorney notes, and billing "
             "status updates. Use for context reasoning, personalization"
    ) 

    email_conversation = dspy.InputField(
        desc="Email exchanges between the client and the attorney/biller/collector. Use for context reasoning and personalization."
    )

    summary: str = dspy.OutputField(
        desc="Actionable summary of the Client across the invoices, notes and financial_data. Accurately mention dates, invoice numbers, amounts when summarizing notes and financial_data.  It should be helpful for the attorneys and provides a up-to-date detailed overview of the the account. "
    )


summarizer = dspy.Predict(ClientSummarization)
summarizer_cot = dspy.ChainOfThought(ClientSummarization)

In [17]:
class InternalContextCompression(dspy.Signature):
    """
    You are Oddr Summarizer, an AI assistant that helps law firms manage their Accounts Receivable. Your job is to generate clear, concise, and helpful summaries for attorneys using only the facts provided.

    You may infer logical next steps or patterns (e.g., payment gaps, lack of follow-up), but do not fabricate or invent any client interactions or internal updates that are not explicitly present in the input.

    If no notes are available, avoid referring to interactions. Focus only on AR status and suggest possible outreach or monitoring based on the financial data.

    Your tone should be professional, factual, and efficient, like a trusted human AR professional writing a briefing. Favor direct, punchy sentences over formal or padded language.

    Compress the provided internal context for downstream client summarization. Frame it as a timeline of events and Keep critical dates, invoice numbers, status changes, promises, blockers, owner/action details, and maintain timeline continuity. Group repetitive events and remove filler.

    Return a single paragraph, no headings, no bullets, and cap output at #target_words words.
    """

    internal_context: str = dspy.InputField(desc="Large mixed internal context from notes and activities.")
    target_words: int = dspy.InputField(desc="Maximum number of words allowed in compressed output.")
    compressed_notes: str = dspy.OutputField(desc="Compressed context string used as notes input for ClientSummarization.")


internal_context_compressor = dspy.Predict(InternalContextCompression)

In [18]:
def data_formatter(df_invoices, df_notes, df_activities, invoice_number):

    notes = df_notes.query(f"invoice_number == {invoice_number}")[['created_on', 'content']].to_records(index=False)
    invoice_data = df_invoices.query(f"invoice_number=={invoice_number}").to_json(index = False, lines = True, orient = 'records')
    activities = df_activities.query(f"invoice_number=={invoice_number}").dropna().drop(columns = ['client_id', 'matter_id', 'invoice_number']).to_markdown(index = False)
    
    formatted_text = f"""
    ### INVOICE DATA: 
    {invoice_data}

    ### NOTES: 
    {notes}

    ### ACTIVITIES: 
    {activities}
    """
    return formatted_text, notes, invoice_data, activities

def data_formatter_csv(df_invoices, df_notes, df_activities, invoice_number):

    notes = df_notes.query(f"invoice_number == {invoice_number}")[['created_on', 'content']].to_csv(index=False)
    invoice_data = df_invoices.query(f"invoice_number=='{invoice_number}'").to_csv(index = False)
    activities = df_activities.query(f"invoice_number=='{invoice_number}'").dropna().drop(columns = ['client_id', 'matter_id', 'invoice_number']).to_csv(index = False)
    
    formatted_text = f"""
    ## INVOICE_NUMBER: {invoice_number}
    ### INVOICE DATA: 
    {invoice_data}

    ### NOTES: 
    {notes}

    ### ACTIVITIES: 
    {activities}

    //
    """
    # return formatted_text
    return formatted_text, notes, invoice_data, activities


def data_formatter_csv_list(df_invoices, df_notes, df_activities, invoice_numbers):

    if not isinstance(invoice_numbers, list):
        invoice_numbers = [invoice_numbers]
    
    invoice_data = df_invoices.query("invoice_number in @invoice_numbers").drop(columns=['client_id', 'matter_id']).to_csv(index=False)
    
    activities = df_activities.query("invoice_number in @invoice_numbers") \
                              .dropna() \
                              .drop(columns=['client_id', "matter_id"]) \
                              .to_csv(index=False)
    
    invoice_numbers = [int(inv_num.split("-")[0]) for inv_num in invoice_numbers]
    # print(invoice_numbers)
    notes = df_notes.query("invoice_number in @invoice_numbers")[[ 'invoice_number', 'created_on', 'content']].to_csv(index=False)
    formatted_text = f"""
    ### INVOICE DATA: 
    {invoice_data}

    ### NOTES: 
    {notes}

    ### ACTIVITIES: 
    {activities}
    """
    return formatted_text, notes, invoice_data, activities

In [19]:
def split_internal_context(internal_context, max_chars=7000, overlap_chars=350):
    text = (internal_context or "").strip()
    if not text:
        return []
    if len(text) <= max_chars:
        return [text]

    chunks = []
    start = 0
    step = max_chars - overlap_chars
    if step <= 0:
        step = max_chars

    while start < len(text):
        end = min(start + max_chars, len(text))
        chunks.append(text[start:end])
        if end >= len(text):
            break
        start += step
    return chunks


def compress_internal_context(internal_context, target_words=200, chunk_chars=7000, overlap_chars=350):
    if not internal_context or not internal_context.strip():
        return ""

    chunks = split_internal_context(internal_context, max_chars=chunk_chars, overlap_chars=overlap_chars)
    if not chunks:
        return ""

    per_chunk_words = max(60, min(140, max(1, target_words // max(1, len(chunks)))))
    chunk_summaries = []

    for idx, chunk in enumerate(chunks, start=1):
        chunk_input = f"Chunk {idx}/{len(chunks)}:\n{chunk}"
        response = internal_context_compressor(
            internal_context=chunk_input,
            target_words=per_chunk_words,
        )
        summary = response.compressed_notes.strip()
        if summary:
            chunk_summaries.append(summary)

    if not chunk_summaries:
        return ""

    merged_context = "\n".join(chunk_summaries)
    final_response = internal_context_compressor(
        internal_context=merged_context,
        target_words=target_words,
    )
    compressed = final_response.compressed_notes.strip()

    if len(compressed.split()) > target_words:
        compressed = internal_context_compressor(
            internal_context=compressed,
            target_words=target_words,
        ).compressed_notes.strip()

    if len(compressed.split()) > target_words:
        compressed = " ".join(compressed.split()[:target_words]).strip()

    return compressed

In [21]:
df_notes.query("client_id == 562116").invoice_number.tolist()

[3825917, 3825917, 3851985]

In [23]:
i = 1

invoice_numbers = df_invoices.groupby(by = "matter_id").agg(list).invoice_number.tolist()
all_invoice_numbers_list = [lst for lst in invoice_numbers if len(lst)>=2]
invoice_numbers = all_invoice_numbers_list[i]
# invoice_numbers = ['3814159', '3814158', '3858831']
invoice_numbers = ['3825917', '3825917', '3851985']
print(invoice_numbers)
# print("Invoice numbers: ", invoice_numbers)
# # formatted_data, notes, invoice_data, activities = data_export_format(df_invoices, df_notes, df_activities, invoice_number)
# # formatted_data, notes, invoice_data, activities = data_formatter_csv(df_invoices, df_notes, df_activities, invoice_number)
# # formatted_data = matter_data_formatter_csv(df_invoices, df_notes, df_activities, invoice_numbers)
formatted_data, notes, invoice_data, activities = data_formatter_csv_list(df_invoices, df_notes, df_activities, invoice_numbers)
print(formatted_data)
print(df_messages.query("client_id == 562116").body.tolist())
# notes, invoice_data = df_extracted['notes'].tolist()[i], df_extracted['financial_data'].tolist()[i]
# internal_context = f"""### Invoice_data:\n{invoice_data} \n\n### NOTES:\n{notes}"""
# print(internal_context)

['3825917', '3825917', '3851985']

    ### INVOICE DATA:
    invoice_number,invoice_amount,ar_amount,submitted_on,due_on,days_overdue,status
3825917,15137.5,15137.5,2025-10-16 20:55:36.604636+00,2025-11-08,42,Viewed
3851985,8080.0,8080.0,2025-11-18 13:54:44.687369+00,2025-12-17,3,Viewed


    ### NOTES:
    invoice_number,created_on,content
3825917,2025-10-16 14:36:21.660739+00:00,I sent <Person> a follow up email that I need him to electronically sign each invoice page before I can send the invoice to the client.
3825917,2025-10-09 20:28:22.562291+00:00,I emailed <Person> to sign off on the invoice before it can go out to the client.
3851985,2025-11-17 16:15:11.826512+00:00,I emailed <Person> to add his signature to the invoice before emailing it to the client.


    ### ACTIVITIES:
    invoice_number,created_on,event_type,name,description
3825917,2025-10-28 08:02:33+00,Event,Email Opened,Opened by <Email>
3825917,2025-10-28 00:58:19+00,Event,Email Opened,Opened by <Email>
3825917,2025-10-28 00:58:17+00,Event,Email Opened,Opened by <Email>
3825917,2025-10-28 00:58:13+00,Event,Email Opened,Opened by <Email>
3825917,2025-10-28 00:57:51+00,Event,Email Opened,Opened by <Email>
3825917,2025-10-24 01:16:11+00,Event,Email Opened,Opened by <Email>
3825917,2025-10-23 11:18:07+00,Event,Email Opened,Opened by <Email>
3825917,2025-10-17 07:14:28+00,Event,Email Opened,Opened by <Email>
3825917,2025-10-17 06:48:00+00,Event,Email Opened,Opened by <Email>
3825917,2025-10-17 06:22:31+00,Event,Email Opened,Opened by <Email>
3825917,2025-10-17 06:21:44+00,Event,Email Opened,Opened by <Email>
3825917,2025-10-17 05:16:56+00,Event,Email Opened,Opened by <Email>
3825917,2025-10-17 05:16:55+00,Event,Email Opened,Opened by <Email>
3825917,2025-10-17 05:16:49+00,Event,Email Opened,Opened by <Email>
3825917,2025-10-17 05:06:53+00,Event,Email Opened,Opened by <Email>
3825917,2025-10-17 05:06:22+00,Event,Email Opened,Opened by <Email>
3825917,2025-10-17 03:36:45+00,Event,Email Opened,Opened by <Email>
3825917,2025-10-17 03:36:45+00,Event,Email Opened,Opened by <Email>
3825917,2025-10-17 03:36:44+00,Event,Email Opened,Opened by <Email>
3825917,2025-10-17 03:36:34+00,Event,Email Opened,Opened by <Email>
3825917,2025-10-17 03:33:06+00,Event,Email Opened,Opened by <Email>
3825917,2025-10-17 03:22:24.204637+00,Event,Viewed,Invoice viewed using the link delivered to [<Email>]
3825917,2025-10-17 01:59:37+00,Event,Email Opened,Opened by <Email>
3825917,2025-10-17 01:54:49+00,Event,Email Opened,Opened by <Email>
3825917,2025-10-17 01:23:49.834796+00,StatusChanged,Viewed,Invoice viewed using the link delivered to [<Email>]
3825917,2025-10-17 01:21:53+00,Event,Email Opened,Opened by <Email>
3825917,2025-10-17 01:21:50+00,Event,Email Opened,Opened by <Email>
3825917,2025-10-17 01:20:06+00,Event,Email Opened,Opened by <Email>
3825917,2025-10-17 01:09:52+00,Event,Email Opened,Opened by <Email>
3825917,2025-10-17 01:09:51+00,Event,Email Opened,Opened by <Email>
3825917,2025-10-17 01:09:08+00,Event,Email Opened,Opened by <Email>
3825917,2025-10-17 01:09:07+00,Event,Email Opened,Opened by <Email>
3825917,2025-10-17 01:08:51+00,StatusChanged,Email Opened,Opened by <Email>
3825917,2025-10-17 00:22:56+00,Event,Email Opened,Opened by <Email>
3825917,2025-10-16 23:09:33+00,StatusChanged,Email Opened,Opened by <Email>
3825917,2025-10-16 20:55:40+00,StatusChanged,Delivered,Delivered to <Email>.
3825917,2025-10-16 20:55:40+00,StatusChanged,Delivered,Delivered to <Email>.
3825917,2025-10-16 20:55:40+00,StatusChanged,Delivered,Delivered to <Email>.
3825917,2025-10-16 20:55:36.612371+00,StatusChanged,Submitted,"Submitted invoice to [<Email>,<Email>,<Email>]."
3825917,2025-10-16 20:55:28.134569+00,Modified,Document uploaded,"Uploaded document [0562116-0000001 Invoice 3825917 (002).pdf], type: [Pdf], version: [<DateTime>:28.1207091Z]"
3825917,2025-10-09 19:20:31.948529+00,Modified,Document uploaded,"Uploaded document [Invoice_3825917.pdf], type: [Pdf], version: [<DateTime>:31<DateTime>]"
3851985,2025-11-26 11:13:48+00,Event,Email Opened,Opened by <Email>
3851985,2025-11-26 09:49:22+00,Event,Email Opened,Opened by <Email>
3851985,2025-11-24 06:39:32.681287+00,Event,Viewed,Invoice viewed using the link delivered to [<Email>]
3851985,2025-11-24 06:35:15.152167+00,StatusChanged,Viewed,Invoice viewed using the link delivered to [<Email>]
3851985,2025-11-24 05:49:51+00,Event,Email Opened,Opened by <Email>
3851985,2025-11-24 05:34:41+00,Event,Email Opened,Opened by <Email>
3851985,2025-11-24 05:34:41+00,Event,Email Opened,Opened by <Email>
3851985,2025-11-21 09:20:46+00,Event,Email Opened,Opened by <Email>
3851985,2025-11-21 09:19:00+00,Event,Email Opened,Opened by <Email>
3851985,2025-11-21 09:14:32+00,Event,Email Opened,Opened by <Email>
3851985,2025-11-21 09:14:12+00,Event,Email Opened,Opened by <Email>
3851985,2025-11-21 09:14:11+00,Event,Email Opened,Opened by <Email>
3851985,2025-11-21 09:13:55+00,StatusChanged,Email Opened,Opened by <Email>
3851985,2025-11-19 13:41:10+00,Event,Email Opened,Opened by <Email>
3851985,2025-11-18 22:28:21+00,Event,Email Opened,Opened by <Email>
3851985,2025-11-18 22:28:02+00,StatusChanged,Email Opened,Opened by <Email>
3851985,2025-11-18 13:54:49+00,StatusChanged,Delivered,Delivered to <Email>.
3851985,2025-11-18 13:54:49+00,StatusChanged,Delivered,Delivered to <Email>.
3851985,2025-11-18 13:54:49+00,StatusChanged,Delivered,Delivered to <Email>.
3851985,2025-11-18 13:54:44.689671+00,StatusChanged,Submitted,"Submitted invoice to [<Email>,<Email>,<Email>]."
3851985,2025-11-18 13:54:35.672151+00,Modified,Document uploaded,"Uploaded document [signed Invoice 3851985.pdf], type: [Pdf], version: [<DateTime>]"
3851985,2025-11-17 14:30:13.002082+00,Modified,Document uploaded,"Uploaded document [Invoice_3851985.pdf], type: [Pdf], version: [<DateTime>]"


['Invoice Submission (External)Hi <Person>, I hope this email finds you well! I have attached invoices 3782330 and 3794119, which were <DateTime> billed in July and August. If you have any questions or need further assistance, please don\'t hesitate to reach out. Thank you, and have a great day! <Person>\u200b\u200b\u200b\u200bBilling SpecialistDirect: <Email> From: <Person> 彭帅 <<Email>> Sent: <DateTime> 2025 1<DateTime> AMTo: <Person>, <Person> <<Email>>; <Person> <<Email>>Cc: <Person> <<Email>>; <Person> <Person> <<Email>>Subject: FW: Your October 2025 Invoice from Husch Blackwell [EXTERNAL EMAIL] <Person> and <Person>: Could you please help with it? Thanks Best regards,<Person>发件人: <Person> <Person> <<Email>> 发送时间: <DateTime>收件人: <Email>抄送: <Person> <<Email>>; <Person>_<Person> <Person> <<Email>>主题: 转发: Your October 2025 Invoice from Husch Blackwell Hi Conley, I received the attached invoice <DateTime> and was surprise to find an outstanding balance on the bill. As I haven\'t received those invoices yet, could you please send them to me? If you have any clue about how it happened, please feel free to let me know. Thanks. Best regards,<Person> 发件人: <Person> <<Email>> 发送时间: <DateTime>收件人: <Person> 彭<Person> <<Email>>主题: Your October 2025 Invoice from <Organization> CAUTION - EXTERNAL EMAIL : Do not click on the link or attachment unless you confirm that the recipient is trusted and the content is secure. Any questions, please report all suspicious emails to "<Email>" as an attachment. A copy of this email was sent to <Email>, <Email> invoice If you have any questions or concerns, please do not hesitate to reach out. We are here to help.Thank you, and have a great day!<Person>mber> Invoice detailsClient name: <Organization> (<Organization>Matter name: BIS Entity ListInvoice #: 3825917 This email is intended for <Organization> (<Organization>We include this personalized information to protect you against phishing. Learn more View your other invoicesClick here to log in to the Oddr Online Invoice Portal to see all your invoices from <Organization>. Do not share this emailPlease do not share this email with others as it contains a secure link to your documents. Questions?For questions about this email or the attached documents, please reach out to your contact at the firm or reply to this email. Technical SupportContact <Email> for help with technical issues. Please note: this address is for technical support only and cannot answer questions about your invoices or any other documents. About <Organization> provides a safe and secure way to access your documents electronically and make payments.Powered by Oddr The above e-mail message, its attachments and included replies (if any) are for the sole use of the intended recipient (s). It may contain information that is privileged, confidential or exempt from disclosure under applicable laws. If you are not an intended recipient, or did not follow the <Organization> for the internal information and file management policy to send this e-mail message, please note that any dissemination, distribution or copying of this message is strictly prohibited and shall notify <Organization> immediately and destroy all copies of this message and its attachments. Any information not related to the official business of <Organization> shall be deemed as neither given nor endorsed by us. Thank you for your cooperation. 本电子邮件、其附件及任何对本电子邮件所作之回复,仅供电子邮件的指定收件人使用。本电子邮件可能包含依法具有特权、保密及不可对外披露的信息。若您并非本电子邮件的指定收件人,或未遵循<Organization>对于内部资讯与档案的管理政策而发送此电子邮件,则任何散播、传送或复制本电子邮件及其附件的行为均被严格禁止,请立即通知<Organization>科技<Organization>并删除本电子邮件及其附件。本电子邮件中任何与<Organization>正式业务无关之信息,不得视为由我们提供或认可。谢谢您的合作。']

In [24]:
email_conversation = df_messages.query("client_id == 562116").body.tolist()
email_conversation

['Invoice Submission (External)Hi <Person>, I hope this email finds you well! I have attached invoices 3782330 and 3794119, which were <DateTime> billed in July and August. If you have any questions or need further assistance, please don\'t hesitate to reach out. Thank you, and have a great day! <Person>\u200b\u200b\u200b\u200bBilling SpecialistDirect: <Email> From: <Person> 彭帅 <<Email>> Sent: <DateTime> 2025 1<DateTime> AMTo: <Person>, <Person> <<Email>>; <Person> <<Email>>Cc: <Person> <<Email>>; <Person> <Person> <<Email>>Subject: FW: Your October 2025 Invoice from Husch Blackwell [EXTERNAL EMAIL] <Person> and <Person>: Could you please help with it? Thanks Best regards,<Person>发件人: <Person> <Person> <<Email>> 发送时间: <DateTime>收件人: <Email>抄送: <Person> <<Email>>; <Person>_<Person> <Person> <<Email>>主题: 转发: Your October 2025 Invoice from Husch Blackwell Hi Conley, I received the attached invoice <DateTime> and was surprise to find an outstanding balance on the bill. As I haven\'t received those invoices yet, could you please send them to me? If you have any clue about how it happened, please feel free to let me know. Thanks. Best regards,<Person> 发件人: <Person> <<Email>> 发送时间: <DateTime>收件人: <Person> 彭<Person> <<Email>>主题: Your October 2025 Invoice from <Organization> CAUTION - EXTERNAL EMAIL : Do not click on the link or attachment unless you confirm that the recipient is trusted and the content is secure. Any questions, please report all suspicious emails to "<Email>" as an attachment. A copy of this email was sent to <Email>, <Email> invoice If you have any questions or concerns, please do not hesitate to reach out. We are here to help.Thank you, and have a great day!<Person>mber> Invoice detailsClient name: <Organization> (<Organization>Matter name: BIS Entity ListInvoice #: 3825917 This email is intended for <Organization> (<Organization>We include this personalized information to protect you against phishing. Learn more View your other invoicesClick here to log in to the Oddr Online Invoice Portal to see all your invoices from <Organization>. Do not share this emailPlease do not share this email with others as it contains a secure link to your documents. Questions?For questions about this email or the attached documents, please reach out to your contact at the firm or reply to this email. Technical SupportContact <Email> for help with technical issues. Please note: this address is for technical support only and cannot answer questions about your invoices or any other documents. About <Organization> provides a safe and secure way to access your documents electronically and make payments.Powered by Oddr The above e-mail message, its attachments and included replies (if any) are for the sole use of the intended recipient (s). It may contain information that is privileged, confidential or exempt from disclosure under applicable laws. If you are not an intended recipient, or did not follow the <Organization> for the internal information and file management policy to send this e-mail message, please note that any dissemination, distribution or copying of this message is strictly prohibited and shall notify <Organization> immediately and destroy all copies of this message and its attachments. Any information not related to the official business of <Organization> shall be deemed as neither given nor endorsed by us. Thank you for your cooperation. 本电子邮件、其附件及任何对本电子邮件所作之回复,仅供电子邮件的指定收件人使用。本电子邮件可能包含依法具有特权、保密及不可对外披露的信息。若您并非本电子邮件的指定收件人,或未遵循<Organization>对于内部资讯与档案的管理政策而发送此电子邮件,则任何散播、传送或复制本电子邮件及其附件的行为均被严格禁止,请立即通知<Organization>科技<Organization>并删除本电子邮件及其附件。本电子邮件中任何与<Organization>正式业务无关之信息,不得视为由我们提供或认可。谢谢您的合作。']

In [27]:
with dspy.context(lm = lm_41_mini.copy(cache = False, temperature = 0.3)):
    response = summarizer_cot(financial_data = invoice_data, notes = notes, email_conversation = email_conversation)
    print(response)

Prediction(
    reasoning='The client currently has two outstanding invoices: invoice 3825917 for $15,137.50, overdue by 42 days as of Nov 08, 2025, and invoice 3851985 for $8,080.00, due Dec 17, 2025, and only 3 days overdue. Both invoices have been viewed by the client. The notes indicate repeated attempts to obtain electronic signatures from a contact person before the invoices could be sent to the client, with the last signature request for invoice 3851985 on Nov 17, 2025. The email conversation reveals the client was surprised by the outstanding balance on the October 2025 invoice and requested copies of the invoices, indicating some confusion or lack of receipt of the invoices. There is no evidence of payment or further client acknowledgment beyond viewing and signature requests. Next steps likely involve confirming receipt of the signed invoices and following up with the client to resolve the overdue balance on invoice 3825917 and ensure timely payment of invoice 3851985.',
    summary='The client has two outstanding invoices totaling over $23,000, with invoice 3825917 overdue by 42 days as of Nov 08, 2025, and invoice 3851985 recently due on Dec 17, 2025. Recent interactions show multiple requests for electronic signatures on invoices before sending them to the client, with the last signature request on Nov 17, 2025, and the client expressed surprise about the outstanding balance in an email, requesting invoice copies. Earlier efforts focused on securing invoice approval, which delayed invoice delivery and may have contributed to payment delays. Follow-up should confirm signed invoice receipt and prompt the client to address the long-overdue invoice 3825917 while monitoring payment of the newer invoice.'
)

In [ ]:
compressed_notes = compress_internal_context(internal_context, target_words=200)
notes_for_summary = compressed_notes if compressed_notes else notes
with dspy.context(lm = lm_41_mini.copy(cache = False, temperature = 0.4)):
    response = summarizer_cot(financial_data = invoice_data, notes = notes_for_summary)

In [45]:
print(compressed_notes)

Client has $16,373 overdue AR across 3 active invoices with an average DSO of 62. September and October invoices remain unpaid despite payments on November and January. Repeated emails from late 2024 to early 2026 addressed payment status and invoice corrections due to address issues. Contact updates occurred with new owners assigned. Client cited multi-level approval delays but promised payment; follow-ups planned if December invoice remains unpaid by 3/15/2026. Separately, a $16,816.29 balance from August to December 2023 is unpaid with no payments received. Multiple emails sent to internal contacts from October to December 2023; client described as "really scattered," but internal contacts committed to pressing client after receiving documents. Client agreed to check payment status; follow-up outreach ongoing with no confirmed payments yet.

In [46]:
response

Prediction(
    reasoning='The client currently has $16,373 in overdue accounts receivable across three active invoices, contributing to an average DSO of 62 days. Despite payments in November and January, the September and October invoices remain unpaid, indicating partial but inconsistent payment behavior. Multiple communications from late 2024 through early 2026 have focused on payment status, invoice corrections, and client contact updates, with the client citing multi-level approval delays but promising payment. There is also a separate older balance of $16,816.29 from August to December 2023 that remains unpaid, with ongoing follow-ups but no confirmed payments. The client is described as "really scattered," and internal contacts have committed to pressing the client further. Follow-up is planned if the December invoice remains unpaid by March 15, 2026, indicating a need for continued monitoring and outreach.',
    summary='The client has **$16,373 overdue across three active invoices**, with an average DSO of 62 days and partial payments made in November and January, but September and October remain unpaid. Recent interactions from late 2024 to early 2026 show ongoing efforts to resolve payment delays caused by multi-level approvals and invoice corrections, with contact updates and promises of payment. An older balance of **$16,816.29 from August to December 2023 remains outstanding**, with multiple follow-ups but no confirmed payments, and internal contacts are actively pressing the client. Continued outreach is necessary, with a key follow-up scheduled if the December invoice is unpaid by **March 15, 2026**.'
)

In [ ]:
from tqdm import tqdm 
import time

invoice_numbers = df_invoices.groupby(by = "matter_id").agg(list).invoice_number.tolist()
all_invoice_numbers_list = [lst for lst in invoice_numbers if len(lst)>=2]

for i in tqdm(range(len(all_invoice_numbers_list))):
    invoice_numbers = all_invoice_numbers_list[i]
    formatted_data, notes, invoice_data, activities = data_formatter_csv_list(df_invoices, df_notes, df_activities, invoice_numbers)
    internal_context = f"""### NOTES:\n{notes}\n\n### ACTIVITIES:\n{activities}"""
    compressed_notes = compress_internal_context(internal_context, target_words=200)
    notes_for_summary = compressed_notes if compressed_notes else notes
    with dspy.context(lm = lm_41_mini.copy(cache = False, temperature = 0.4)):
        response = summarizer_cot(financial_data = invoice_data, notes = notes_for_summary)
        # print(response)
    time.sleep(5)

  0%|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | 0/46 [00:00<?, ?it/s]

 11%|████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | 5/46 [00:49<06:30,  9.52s/it]

{
    "resource_metrics": [
        {
            "resource": {
                "attributes": {
                    "telemetry.sdk.language": "python",
                    "telemetry.sdk.name": "openlit",
                    "telemetry.sdk.version": "1.39.1",
                    "service.name": "default",
                    "deployment.environment": "default"
                },
                "schema_url": ""
            },
            "scope_metrics": [
                {
                    "scope": {
                        "name": "opentelemetry.instrumentation.httpx",
                        "version": "0.60b1",
                        "schema_url": "https://opentelemetry.io/schemas/1.11.0",
                        "attributes": null
                    },
                    "metrics": [
                        {
                            "name": "http.client.duration",
                            "description": "measures the duration of the outbound HTTP request",
                            "unit": "ms",
                            "data": {
                                "data_points": [
                                    {
                                        "attributes": {
                                            "http.method": "POST",
                                            "http.scheme": "https",
                                            "http.status_code": 200
                                        },
                                        "start_time_unix_nano": 1770052629790336912,
                                        "time_unix_nano": 1770053395954900904,
                                        "count": 53,
                                        "sum": 146975,
                                        "bucket_counts": [
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            23,
                                            28,
                                            2,
                                            0,
                                            0
                                        ],
                                        "explicit_bounds": [
                                            0.0,
                                            5.0,
                                            10.0,
                                            25.0,
                                            50.0,
                                            75.0,
                                            100.0,
                                            250.0,
                                            500.0,
                                            750.0,
                                            1000.0,
                                            2500.0,
                                            5000.0,
                                            7500.0,
                                            10000.0
                                        ],
                                        "min": 1738,
                                        "max": 6302,
                                        "exemplars": [
                                            {
                                                "filtered_attributes": {},
                                                "value": 4070,
                                                "time_unix_nano": 1770053390449153294,
                                                "span_id": 8238262370453951816,
                                                "trace_id": 17763945482865803774465902404169529408
                                            },
                                            {
                                                "filtered_attributes": {},
                                                "value": 5151,
                                                "time_unix_nano": 1770053372260462731,
                                                "span_id": 11632969206361399490,
                                                "trace_id": 15190217526730554274094419514651239073
                                            }
                                        ]
                                    }
                                ],
                                "aggregation_temporality": 2
                            }
                        }
                    ],
                    "schema_url": "https://opentelemetry.io/schemas/1.11.0"
                }
            ],
            "schema_url": ""
        }
    ]
}

 26%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | 12/46 [01:49<04:46,  8.42s/it]

{
    "resource_metrics": [
        {
            "resource": {
                "attributes": {
                    "telemetry.sdk.language": "python",
                    "telemetry.sdk.name": "openlit",
                    "telemetry.sdk.version": "1.39.1",
                    "service.name": "default",
                    "deployment.environment": "default"
                },
                "schema_url": ""
            },
            "scope_metrics": [
                {
                    "scope": {
                        "name": "opentelemetry.instrumentation.httpx",
                        "version": "0.60b1",
                        "schema_url": "https://opentelemetry.io/schemas/1.11.0",
                        "attributes": null
                    },
                    "metrics": [
                        {
                            "name": "http.client.duration",
                            "description": "measures the duration of the outbound HTTP request",
                            "unit": "ms",
                            "data": {
                                "data_points": [
                                    {
                                        "attributes": {
                                            "http.method": "POST",
                                            "http.scheme": "https",
                                            "http.status_code": 200
                                        },
                                        "start_time_unix_nano": 1770052629790336912,
                                        "time_unix_nano": 1770053455958701136,
                                        "count": 60,
                                        "sum": 171517,
                                        "bucket_counts": [
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            23,
                                            35,
                                            2,
                                            0,
                                            0
                                        ],
                                        "explicit_bounds": [
                                            0.0,
                                            5.0,
                                            10.0,
                                            25.0,
                                            50.0,
                                            75.0,
                                            100.0,
                                            250.0,
                                            500.0,
                                            750.0,
                                            1000.0,
                                            2500.0,
                                            5000.0,
                                            7500.0,
                                            10000.0
                                        ],
                                        "min": 1738,
                                        "max": 6302,
                                        "exemplars": [
                                            {
                                                "filtered_attributes": {},
                                                "value": 3366,
                                                "time_unix_nano": 1770053450826893651,
                                                "span_id": 372122290553595505,
                                                "trace_id": 36038836944833068553360510096750308825
                                            }
                                        ]
                                    }
                                ],
                                "aggregation_temporality": 2
                            }
                        }
                    ],
                    "schema_url": "https://opentelemetry.io/schemas/1.11.0"
                }
            ],
            "schema_url": ""
        }
    ]
}

 39%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | 18/46 [02:47<04:34,  9.81s/it]

{
    "resource_metrics": [
        {
            "resource": {
                "attributes": {
                    "telemetry.sdk.language": "python",
                    "telemetry.sdk.name": "openlit",
                    "telemetry.sdk.version": "1.39.1",
                    "service.name": "default",
                    "deployment.environment": "default"
                },
                "schema_url": ""
            },
            "scope_metrics": [
                {
                    "scope": {
                        "name": "opentelemetry.instrumentation.httpx",
                        "version": "0.60b1",
                        "schema_url": "https://opentelemetry.io/schemas/1.11.0",
                        "attributes": null
                    },
                    "metrics": [
                        {
                            "name": "http.client.duration",
                            "description": "measures the duration of the outbound HTTP request",
                            "unit": "ms",
                            "data": {
                                "data_points": [
                                    {
                                        "attributes": {
                                            "http.method": "POST",
                                            "http.scheme": "https",
                                            "http.status_code": 200
                                        },
                                        "start_time_unix_nano": 1770052629790336912,
                                        "time_unix_nano": 1770053515962126945,
                                        "count": 66,
                                        "sum": 198772,
                                        "bucket_counts": [
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            23,
                                            40,
                                            3,
                                            0,
                                            0
                                        ],
                                        "explicit_bounds": [
                                            0.0,
                                            5.0,
                                            10.0,
                                            25.0,
                                            50.0,
                                            75.0,
                                            100.0,
                                            250.0,
                                            500.0,
                                            750.0,
                                            1000.0,
                                            2500.0,
                                            5000.0,
                                            7500.0,
                                            10000.0
                                        ],
                                        "min": 1738,
                                        "max": 7022,
                                        "exemplars": [
                                            {
                                                "filtered_attributes": {},
                                                "value": 4414,
                                                "time_unix_nano": 1770053508727145206,
                                                "span_id": 123494109420098093,
                                                "trace_id": 19725702599003166728830651525119200638
                                            },
                                            {
                                                "filtered_attributes": {},
                                                "value": 7022,
                                                "time_unix_nano": 1770053499221128767,
                                                "span_id": 10013444919656517109,
                                                "trace_id": 182637742232021225778663322975544569071
                                            }
                                        ]
                                    }
                                ],
                                "aggregation_temporality": 2
                            }
                        }
                    ],
                    "schema_url": "https://opentelemetry.io/schemas/1.11.0"
                }
            ],
            "schema_url": ""
        }
    ]
}

 54%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                                                                                                                                                                                                                                                                                                                                                       | 25/46 [03:47<03:05,  8.81s/it]

{
    "resource_metrics": [
        {
            "resource": {
                "attributes": {
                    "telemetry.sdk.language": "python",
                    "telemetry.sdk.name": "openlit",
                    "telemetry.sdk.version": "1.39.1",
                    "service.name": "default",
                    "deployment.environment": "default"
                },
                "schema_url": ""
            },
            "scope_metrics": [
                {
                    "scope": {
                        "name": "opentelemetry.instrumentation.httpx",
                        "version": "0.60b1",
                        "schema_url": "https://opentelemetry.io/schemas/1.11.0",
                        "attributes": null
                    },
                    "metrics": [
                        {
                            "name": "http.client.duration",
                            "description": "measures the duration of the outbound HTTP request",
                            "unit": "ms",
                            "data": {
                                "data_points": [
                                    {
                                        "attributes": {
                                            "http.method": "POST",
                                            "http.scheme": "https",
                                            "http.status_code": 200
                                        },
                                        "start_time_unix_nano": 1770052629790336912,
                                        "time_unix_nano": 1770053575966920127,
                                        "count": 73,
                                        "sum": 222892,
                                        "bucket_counts": [
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            24,
                                            46,
                                            3,
                                            0,
                                            0
                                        ],
                                        "explicit_bounds": [
                                            0.0,
                                            5.0,
                                            10.0,
                                            25.0,
                                            50.0,
                                            75.0,
                                            100.0,
                                            250.0,
                                            500.0,
                                            750.0,
                                            1000.0,
                                            2500.0,
                                            5000.0,
                                            7500.0,
                                            10000.0
                                        ],
                                        "min": 1738,
                                        "max": 7022,
                                        "exemplars": [
                                            {
                                                "filtered_attributes": {},
                                                "value": 2464,
                                                "time_unix_nano": 1770053533524136767,
                                                "span_id": 8385273588227953286,
                                                "trace_id": 131928097937391402087987509320734849093
                                            },
                                            {
                                                "filtered_attributes": {},
                                                "value": 3622,
                                                "time_unix_nano": 1770053568568694017,
                                                "span_id": 15995926977525176876,
                                                "trace_id": 253000322983749394931178584241214220932
                                            }
                                        ]
                                    }
                                ],
                                "aggregation_temporality": 2
                            }
                        }
                    ],
                    "schema_url": "https://opentelemetry.io/schemas/1.11.0"
                }
            ],
            "schema_url": ""
        }
    ]
}

 67%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                                                                                                                                                                                                                         | 31/46 [04:43<02:21,  9.43s/it]

{
    "resource_metrics": [
        {
            "resource": {
                "attributes": {
                    "telemetry.sdk.language": "python",
                    "telemetry.sdk.name": "openlit",
                    "telemetry.sdk.version": "1.39.1",
                    "service.name": "default",
                    "deployment.environment": "default"
                },
                "schema_url": ""
            },
            "scope_metrics": [
                {
                    "scope": {
                        "name": "opentelemetry.instrumentation.httpx",
                        "version": "0.60b1",
                        "schema_url": "https://opentelemetry.io/schemas/1.11.0",
                        "attributes": null
                    },
                    "metrics": [
                        {
                            "name": "http.client.duration",
                            "description": "measures the duration of the outbound HTTP request",
                            "unit": "ms",
                            "data": {
                                "data_points": [
                                    {
                                        "attributes": {
                                            "http.method": "POST",
                                            "http.scheme": "https",
                                            "http.status_code": 200
                                        },
                                        "start_time_unix_nano": 1770052629790336912,
                                        "time_unix_nano": 1770053635971834268,
                                        "count": 80,
                                        "sum": 253073,
                                        "bucket_counts": [
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            24,
                                            53,
                                            3,
                                            0,
                                            0
                                        ],
                                        "explicit_bounds": [
                                            0.0,
                                            5.0,
                                            10.0,
                                            25.0,
                                            50.0,
                                            75.0,
                                            100.0,
                                            250.0,
                                            500.0,
                                            750.0,
                                            1000.0,
                                            2500.0,
                                            5000.0,
                                            7500.0,
                                            10000.0
                                        ],
                                        "min": 1738,
                                        "max": 7022,
                                        "exemplars": [
                                            {
                                                "filtered_attributes": {},
                                                "value": 4163,
                                                "time_unix_nano": 1770053634504781228,
                                                "span_id": 12971424178132982232,
                                                "trace_id": 284234049300990085957714728890290827536
                                            }
                                        ]
                                    }
                                ],
                                "aggregation_temporality": 2
                            }
                        }
                    ],
                    "schema_url": "https://opentelemetry.io/schemas/1.11.0"
                }
            ],
            "schema_url": ""
        }
    ]
}

 83%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                                                                       | 38/46 [05:49<01:14,  9.26s/it]

{
    "resource_metrics": [
        {
            "resource": {
                "attributes": {
                    "telemetry.sdk.language": "python",
                    "telemetry.sdk.name": "openlit",
                    "telemetry.sdk.version": "1.39.1",
                    "service.name": "default",
                    "deployment.environment": "default"
                },
                "schema_url": ""
            },
            "scope_metrics": [
                {
                    "scope": {
                        "name": "opentelemetry.instrumentation.httpx",
                        "version": "0.60b1",
                        "schema_url": "https://opentelemetry.io/schemas/1.11.0",
                        "attributes": null
                    },
                    "metrics": [
                        {
                            "name": "http.client.duration",
                            "description": "measures the duration of the outbound HTTP request",
                            "unit": "ms",
                            "data": {
                                "data_points": [
                                    {
                                        "attributes": {
                                            "http.method": "POST",
                                            "http.scheme": "https",
                                            "http.status_code": 200
                                        },
                                        "start_time_unix_nano": 1770052629790336912,
                                        "time_unix_nano": 1770053695978717791,
                                        "count": 86,
                                        "sum": 278654,
                                        "bucket_counts": [
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            24,
                                            58,
                                            4,
                                            0,
                                            0
                                        ],
                                        "explicit_bounds": [
                                            0.0,
                                            5.0,
                                            10.0,
                                            25.0,
                                            50.0,
                                            75.0,
                                            100.0,
                                            250.0,
                                            500.0,
                                            750.0,
                                            1000.0,
                                            2500.0,
                                            5000.0,
                                            7500.0,
                                            10000.0
                                        ],
                                        "min": 1738,
                                        "max": 7022,
                                        "exemplars": [
                                            {
                                                "filtered_attributes": {},
                                                "value": 3973,
                                                "time_unix_nano": 1770053690666393645,
                                                "span_id": 8202151235334146337,
                                                "trace_id": 293349959167918687635520999013077733709
                                            },
                                            {
                                                "filtered_attributes": {},
                                                "value": 5232,
                                                "time_unix_nano": 1770053673162935844,
                                                "span_id": 110993683418485818,
                                                "trace_id": 178124235284206303854789147701091134182
                                            }
                                        ]
                                    }
                                ],
                                "aggregation_temporality": 2
                            }
                        }
                    ],
                    "schema_url": "https://opentelemetry.io/schemas/1.11.0"
                }
            ],
            "schema_url": ""
        }
    ]
}

 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                         | 44/46 [06:47<00:19,  9.51s/it]

{
    "resource_metrics": [
        {
            "resource": {
                "attributes": {
                    "telemetry.sdk.language": "python",
                    "telemetry.sdk.name": "openlit",
                    "telemetry.sdk.version": "1.39.1",
                    "service.name": "default",
                    "deployment.environment": "default"
                },
                "schema_url": ""
            },
            "scope_metrics": [
                {
                    "scope": {
                        "name": "opentelemetry.instrumentation.httpx",
                        "version": "0.60b1",
                        "schema_url": "https://opentelemetry.io/schemas/1.11.0",
                        "attributes": null
                    },
                    "metrics": [
                        {
                            "name": "http.client.duration",
                            "description": "measures the duration of the outbound HTTP request",
                            "unit": "ms",
                            "data": {
                                "data_points": [
                                    {
                                        "attributes": {
                                            "http.method": "POST",
                                            "http.scheme": "https",
                                            "http.status_code": 200
                                        },
                                        "start_time_unix_nano": 1770052629790336912,
                                        "time_unix_nano": 1770053755982806396,
                                        "count": 92,
                                        "sum": 306060,
                                        "bucket_counts": [
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            0,
                                            24,
                                            61,
                                            7,
                                            0,
                                            0
                                        ],
                                        "explicit_bounds": [
                                            0.0,
                                            5.0,
                                            10.0,
                                            25.0,
                                            50.0,
                                            75.0,
                                            100.0,
                                            250.0,
                                            500.0,
                                            750.0,
                                            1000.0,
                                            2500.0,
                                            5000.0,
                                            7500.0,
                                            10000.0
                                        ],
                                        "min": 1738,
                                        "max": 7022,
                                        "exemplars": [
                                            {
                                                "filtered_attributes": {},
                                                "value": 3099,
                                                "time_unix_nano": 1770053748705788178,
                                                "span_id": 10879650191824051080,
                                                "trace_id": 22089288424755096544244006649118825592
                                            },
                                            {
                                                "filtered_attributes": {},
                                                "value": 5261,
                                                "time_unix_nano": 1770053740498005424,
                                                "span_id": 9747460583485185940,
                                                "trace_id": 253228773103510489751970479806848487351
                                            }
                                        ]
                                    }
                                ],
                                "aggregation_temporality": 2
                            }
                        }
                    ],
                    "schema_url": "https://opentelemetry.io/schemas/1.11.0"
                }
            ],
            "schema_url": ""
        }
    ]
}

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 46/46 [07:06<00:00,  9.27s/it]

In [10]:
with dspy.context(lm = lm_4o_mini.copy(cache = False, temperature = 0.4)):
    response = summarizer(financial_data = invoice_data, notes = compressed_notes)
    print(response)

Prediction(
    summary='The current Accounts Receivable status shows **three outstanding invoices** totaling **$36,240.50**, with the most overdue invoice (3830244) from **Oct 16, 2025**, now **36 days overdue**. The latest invoice (3849710) was submitted on **Nov 13, 2025**, and is due on **Dec 13, 2025**, while the most recent one (3869038) has just been delivered and is due on **Jan 09, 2026**. There have been no recent client interactions noted, indicating a potential gap in follow-up communication. It is advisable to reach out to the client to discuss the overdue invoice and confirm their receipt of the latest invoice to ensure timely payment.'
)

In [11]:
with dspy.context(lm = lm_41_mini.copy(cache = False, temperature = 0.4)):
    response = summarizer(financial_data = invoice_data, notes = compressed_notes)
    print(response)

Prediction(
    summary='The client currently has three outstanding invoices totaling **$34,240.50**, with the oldest invoice 3830244 overdue by **36 days** as of Nov 14, 2025, and invoice 3849710 recently overdue by **7 days** as of Dec 13, 2025. Invoice 3869038 was delivered on Dec 10, 2025, and is not yet due. There are no notes or recorded interactions to clarify reasons for delays or confirm payment plans. Immediate follow-up is recommended to address the significantly overdue invoice 3830244 and to confirm payment status on invoice 3849710 to prevent further aging.'
)

In [16]:
with dspy.context(lm = lm_5_mini):
    response = summarizer_cot(financial_data = invoice_data, notes = compressed_notes)
    print(response)

Prediction(
    reasoning='I parsed the provided CSV financial_data to extract three immutable AR line items: invoice numbers, invoice amounts, AR amounts, submitted_on and due_on dates, and days overdue. There were no entries in the notes section, so I did not assume any client interactions or internal updates beyond the financial facts. I computed the total outstanding by summing the AR amounts ($14,523.00 + $24,114.50 + $185.00 = $38,822.50) and identified the overdue status per row (84 and 20 days overdue as provided, and one invoice not yet overdue). Based on the instructions, I prioritized presenting a concise timeline-style summary with dates in the required format and offering clear next-step recommendations without inventing any interactions.',
    summary='**$38,822.50 outstanding** across three invoices: **#3801528 $14,523.00** (submitted Aug 28,2025; due Sep 27,2025 — **84 days overdue**), **#3841429 $24,114.50** (submitted Nov 10,2025; due Nov 30,2025 — **20 days overdue**), and **#3871593 $185.00** (submitted Dec 15,2025; due Jan 14,2026). There are **no notes or recorded client interactions** in the provided notes file to explain payment status or any promised remittance. The most urgent liabilities are **#3801528** (significantly past due) and **#3841429** (recently past due); **#3871593** remains current through Jan 14,2026. Recommend immediate outreach (email + phone) for **#3801528** and **#3841429** within 5 business days, monitor **#3871593** through its due date (Jan 14,2026), and escalate to collections or formal demand if no payment/response within 14 days.'
)